package store

import (
	"context"
	"kpcms/server/core/document"
	"os"
	"path/filepath"
	"testing"
)

func TestFileDocumentRepository_Create(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := document.NewNamingStrategyCaseDDDD("case")
	repo, err := New(tmpBase, "", strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &document.Document{Title: "Test Document"}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	metaPath := filepath.Join(tmpBase, doc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		t.Errorf("expected meta.json to exist at %s", metaPath)
	}

	retrieved, err := repo.GetByUUID(ctx, doc.UUID)
	if err != nil {
		t.Fatalf("GetByUUID failed: %v", err)
	}
	if retrieved.Title != doc.Title {
		t.Errorf("expected title %s, got %s", doc.Title, retrieved.Title)
	}
}

func TestFileDocumentRepository_Create_IgnoresUserFolderName(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := document.NewNamingStrategyCaseDDDD("case")
	repo, err := New(tmpBase, "", strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &document.Document{
		Title:      "Test Document 2",
		FolderName: "user_supplied_folder", // should be ignored
	}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	// The folder name should be generated by the strategy, not the user-supplied value
	if doc.FolderName == "user_supplied_folder" {
		t.Errorf("expected FolderName to be generated, but got user-supplied value")
	}

	// Check that the generated folder exists and contains meta.json
	metaPath := filepath.Join(tmpBase, doc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		t.Errorf("expected meta.json to exist at %s", metaPath)
	}
}
