package store

import (
	"bytes"
	"context"
	"io"
	"kpcms/server/core/document"
	"os"
	"path/filepath"
	"testing"
)

func TestFileDocumentRepository_Create(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := document.NewNamingStrategyCaseDDDD("case")
	repo, err := New(tmpBase, "", strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &document.Document{Title: "Test Document"}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	metaPath := filepath.Join(tmpBase, doc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		t.Errorf("expected meta.json to exist at %s", metaPath)
	}

	retrieved, err := repo.GetByUUID(ctx, doc.UUID)
	if err != nil {
		t.Fatalf("GetByUUID failed: %v", err)
	}
	if retrieved.Title != doc.Title {
		t.Errorf("expected title %s, got %s", doc.Title, retrieved.Title)
	}
}

func TestFileDocumentRepository_Create_IgnoresUserFolderName(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := document.NewNamingStrategyCaseDDDD("case")
	repo, err := New(tmpBase, "", strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &document.Document{
		Title:      "Test Document 2",
		FolderName: "user_supplied_folder", // should be ignored
	}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	// The folder name should be generated by the strategy, not the user-supplied value
	if doc.FolderName == "user_supplied_folder" {
		t.Errorf("expected FolderName to be generated, but got user-supplied value")
	}

	// Check that the generated folder exists and contains meta.json
	metaPath := filepath.Join(tmpBase, doc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		t.Errorf("expected meta.json to exist at %s", metaPath)
	}
}

func TestFileDocumentRepository_RestartReload_CurrentBehavior(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := document.NewNamingStrategyCaseDDDD("case")
	repo, err := New(tmpBase, "", strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &document.Document{Title: "Restart Smoke Test"}
	createdDoc, err := repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	fileName := "phase1-verification.txt"
	fileContent := []byte("phase 1 verification content")
	if err := repo.UploadFile(ctx, createdDoc.UUID, fileName, bytes.NewReader(fileContent)); err != nil {
		t.Fatalf("UploadFile failed: %v", err)
	}

	metaPath := filepath.Join(tmpBase, createdDoc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); err != nil {
		t.Fatalf("expected meta.json to exist: %v", err)
	}

	filesPath := filepath.Join(tmpBase, createdDoc.FolderName, "files.json")
	if _, err := os.Stat(filesPath); err != nil {
		t.Fatalf("expected files.json to exist: %v", err)
	}

	// Simulate a restart by constructing a new repository from the same folder.
	reloadedRepo, err := New(tmpBase, "", strategy)
	if err != nil {
		t.Fatalf("failed to reload repo: %v", err)
	}

	reloaded, err := reloadedRepo.GetByUUID(ctx, createdDoc.UUID)
	if err != nil {
		t.Fatalf("GetByUUID after restart failed: %v", err)
	}
	if reloaded.Title != doc.Title {
		t.Fatalf("expected title %q after restart, got %q", doc.Title, reloaded.Title)
	}
	if len(reloaded.Files) != 1 {
		t.Fatalf("expected 1 file after restart, got %d", len(reloaded.Files))
	}
	if reloaded.Files[0].FileName != fileName {
		t.Fatalf("expected file %q after restart, got %q", fileName, reloaded.Files[0].FileName)
	}

	rc, err := reloadedRepo.DownloadFile(ctx, createdDoc.UUID, fileName)
	if err != nil {
		t.Fatalf("DownloadFile after restart failed: %v", err)
	}
	defer rc.Close()

	data, err := io.ReadAll(rc)
	if err != nil {
		t.Fatalf("failed to read downloaded file: %v", err)
	}
	if string(data) != string(fileContent) {
		t.Fatalf("expected downloaded content %q, got %q", string(fileContent), string(data))
	}
}
