package document

import (
	"context"
	"os"
	"path/filepath"
	"testing"
)

func TestFileDocumentRepository_Create(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := NewNamingStrategyCaseDDDD("case")
	repo, err := NewFileDocumentRepository(tmpBase, strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &Document{Title: "Test Document"}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	metaPath := filepath.Join(tmpBase, doc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		t.Errorf("expected meta.json to exist at %s", metaPath)
	}

	retrieved, err := repo.GetByUUID(ctx, doc.UUID)
	if err != nil {
		t.Fatalf("GetByUUID failed: %v", err)
	}
	if retrieved.Title != doc.Title {
		t.Errorf("expected title %s, got %s", doc.Title, retrieved.Title)
	}
}

func TestFileDocumentRepository_Create_IgnoresUserFolderName(t *testing.T) {
	tmpBase := t.TempDir()

	strategy := NewNamingStrategyCaseDDDD("case")
	repo, err := NewFileDocumentRepository(tmpBase, strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &Document{
		Title:      "Test Document 2",
		FolderName: "user_supplied_folder", // should be ignored
	}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	// The folder name should be generated by the strategy, not the user-supplied value
	if doc.FolderName == "user_supplied_folder" {
		t.Errorf("expected FolderName to be generated, but got user-supplied value")
	}

	// Check that the generated folder exists and contains meta.json
	metaPath := filepath.Join(tmpBase, doc.FolderName, "meta.json")
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		t.Errorf("expected meta.json to exist at %s", metaPath)
	}
}

// should ignore user-provided code and generate according to naming strategy
func TestFileDocumentRepository_Create_IgnoresUserCode(t *testing.T) {
	userSuppliedCode := "9999"
	tmpBase := t.TempDir()

	strategy := NewNamingStrategyCaseDDDD("case")
	repo, err := NewFileDocumentRepository(tmpBase, strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	ctx := context.Background()
	doc := &Document{
		Title: "Test Document 2",
		Code:  userSuppliedCode, // should be ignored
	}

	_, err = repo.Create(ctx, doc)
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	// The code should be generated by the strategy, not the user-supplied code
	if doc.Code == userSuppliedCode {
		t.Errorf("expected Code to be generated, but got user-supplied code")
	}
}

func TestFileDocumentRepository_ReloadCache(t *testing.T) {
	tmpBase := t.TempDir()

	docFolder := filepath.Join(tmpBase, "existing_doc")
	os.MkdirAll(docFolder, 0755)

	metaData := `{"uuid": "old-uuid", "code": "OLD-01", "folder_name": "existing_doc", "title": "Old Doc"}`
	os.WriteFile(filepath.Join(docFolder, "meta.json"), []byte(metaData), 0644)

	strategy := NewNamingStrategyCaseDDDD("case")
	repo, err := NewFileDocumentRepository(tmpBase, strategy)
	if err != nil {
		t.Fatalf("failed to init repo: %v", err)
	}

	_, err = repo.GetByUUID(context.Background(), "old-uuid")
	if err != nil {
		t.Errorf("repo failed to load existing document into cache: %v", err)
	}
}
