// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartBackendServer(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartBackendServer'](arg1, arg2, arg3, arg4, arg5);
}

export function StartWebServer(arg1, arg2) {
  return window['go']['main']['App']['StartWebServer'](arg1, arg2);
}

export function StopBackendServer() {
  return window['go']['main']['App']['StopBackendServer']();
}

export function StopWebServer() {
  return window['go']['main']['App']['StopWebServer']();
}
