// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfigDirectory():Promise<string>;

export function GetExecutableDir():Promise<string>;

export function GetNetworkInfo():Promise<Record<string, any>>;

export function LoadSavedConfig():Promise<main.Config>;

export function Log(arg1:string):Promise<void>;

export function SaveConfiguration(arg1:string,arg2:number,arg3:string,arg4:number,arg5:string,arg6:string,arg7:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartBackendServer(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<main.StartBackendServerResult>;

export function StartWebServer(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function StopBackendServer():Promise<void>;

export function StopWebServer():Promise<void>;
