// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigDirectory() {
  return window['go']['main']['App']['GetConfigDirectory']();
}

export function GetExecutableDir() {
  return window['go']['main']['App']['GetExecutableDir']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function LoadSavedConfig() {
  return window['go']['main']['App']['LoadSavedConfig']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function SaveConfiguration(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveConfiguration'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartBackendServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['StartBackendServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StartWebServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartWebServer'](arg1, arg2, arg3, arg4);
}

export function StopBackendServer() {
  return window['go']['main']['App']['StopBackendServer']();
}

export function StopWebServer() {
  return window['go']['main']['App']['StopWebServer']();
}
