// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetExecutableDir():Promise<string>;

export function GetNetworkInfo():Promise<Record<string, any>>;

export function Log(arg1:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartBackendServer(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function StartWebServer(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function StopBackendServer():Promise<void>;

export function StopWebServer():Promise<void>;
