name: Windows Build
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.5'
          cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build 

      - name: Build Wails App
        run: wails build -platform windows/amd64

      - name: Add SignTool to PATH
        uses: KamaranL/add-signtool-action@v1

      - name: Sign Wails App
        shell: powershell
        env:
          PFX_DATA: ${{ secrets.PFX_DATA }}
          PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}
        run: |
          $pfxPath = Join-Path $pwd "tuf-devs.pfx"
          $bytes = [System.Convert]::FromBase64String($env:PFX_DATA)
          [System.IO.File]::WriteAllBytes($pfxPath, $bytes)
          
          $exePath = Get-ChildItem -Path "build/bin/*.exe" | Select-Object -ExpandProperty FullName -First 1
          
          if (-not $exePath) {
              Write-Error "Could not find the executable in build/bin/"
              exit 1
          }

          Write-Host "Signing: $exePath"
          
          signtool sign /v /debug /f $pfxPath /p $env:PFX_PASSWORD /fd sha256 /tr http://timestamp.digicert.com /td sha256 "$exePath"
          
          Remove-Item $pfxPath

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: wails-windows-build
          path: build/bin/*.exe